services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  django:
    image: kojamad28/postgres-drf
    container_name: drf
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
